"""empty message

Revision ID: 32f4b69dc2ec
Revises: None
Create Date: 2015-05-18 12:21:05.002532

"""

# revision identifiers, used by Alembic.
revision = '32f4b69dc2ec'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=True),
    sa.Column('last_name', sa.String(length=30), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('parcels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('size', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('water', sa.Boolean(), nullable=True),
    sa.Column('zoning', sa.String(length=80), nullable=False),
    sa.Column('geometry', sa.String(length=5000), nullable=False),
    sa.Column('developmentPlan', sa.String(length=400), nullable=True),
    sa.Column('restrictions', sa.String(length=400), nullable=True),
    sa.Column('image', sa.String(length=400), nullable=True),
    sa.Column('address', sa.String(length=400), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles')
    op.drop_table('parcels')
    op.drop_table('users')
    ### end Alembic commands ###
